export const QUIZ_QUESTIONS = [
  { q: "What architectural pattern do most large language models use?", options: ["CNN", "Transformer", "RNN", "GAN"], correct: 1, explanation: "The Transformer architecture, introduced in 'Attention Is All You Need' (2017), is the backbone of virtually all modern LLMs." },
  { q: "What does 'MoE' stand for in model architectures like Mixtral?", options: ["Model of Efficiency", "Mixture of Experts", "Method of Encoding", "Module of Evaluation"], correct: 1, explanation: "Mixture of Experts (MoE) routes inputs to specialized sub-networks, enabling larger model capacity with less compute per token." },
  { q: "Which technique reduces model size while preserving most accuracy?", options: ["Quantization", "Tokenization", "Augmentation", "Normalization"], correct: 0, explanation: "Quantization reduces precision of weights (e.g., FP16 → INT4), dramatically shrinking model size and inference cost." },
  { q: "What is 'RLHF' used for in training LLMs?", options: ["Reducing latency", "Aligning outputs with human preferences", "Compressing weights", "Generating training data"], correct: 1, explanation: "Reinforcement Learning from Human Feedback (RLHF) fine-tunes models to produce outputs humans prefer, improving helpfulness and safety." },
  { q: "In RAG systems, what does the 'R' stand for?", options: ["Recursive", "Retrieval", "Reinforced", "Recurrent"], correct: 1, explanation: "Retrieval-Augmented Generation fetches relevant documents from an external store before generating, grounding responses in real data." },
  { q: "What is the primary purpose of 'attention' in Transformers?", options: ["Compress sequences", "Weight token relevance dynamically", "Normalize gradients", "Reduce vocabulary size"], correct: 1, explanation: "Self-attention lets each token attend to all others, dynamically weighting which parts of the input are most relevant for each output position." },
  { q: "Which company released the original GPT-1 paper?", options: ["Google", "Meta", "OpenAI", "Anthropic"], correct: 2, explanation: "OpenAI published 'Improving Language Understanding by Generative Pre-Training' in 2018, introducing GPT-1." },
  { q: "What does a 'context window' refer to?", options: ["Training dataset size", "Max tokens processed in one pass", "GPU memory allocation", "Number of model layers"], correct: 1, explanation: "The context window is the maximum number of tokens (input + output) a model can process in a single inference call." },
  { q: "What is 'prompt engineering'?", options: ["Building GPU clusters", "Crafting inputs to elicit better outputs", "Training from scratch", "Designing model architectures"], correct: 1, explanation: "Prompt engineering is the practice of designing and iterating on inputs to steer LLM behavior without modifying model weights." },
  { q: "Which approach lets you adapt a pretrained model with minimal trainable parameters?", options: ["LoRA", "Dropout", "Batch norm", "Gradient clipping"], correct: 0, explanation: "LoRA (Low-Rank Adaptation) injects small trainable matrices into frozen layers, enabling efficient fine-tuning with <1% of original parameters." },
];
